### ISSUE TITLE
CONTRIBUTORS.md file needed

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#11]
I'd like to acknowledge people who help with this project by adding a `CONTRIBUTORS.md` file.

A link to it in README.md (near the contact section) and in CONTRIBUTING.md (at the top)

At the top of `CONTRIBUTORS.md`, a link to:
https://github.com/andy5995/mhwkb/graphs/contributors

Followed by a list.

The format of the list of contributors should just be:

`nickname (full name)`

Full name optional of course, depending on the user's preference.

And that should be hyperlinked to their home page or GitHub profile.

We need @derekkramer and @SunyataZero  @nikje94 on there.

**Comment by Nefari0uss** [comment]
If this is still open I can make a `CONTRIBUTORS.md` doc.
