### ISSUE TITLE
01add handheld_device_apps.md

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#16]
Please add `01handheld_device_apps.md` to the [Knowledge Base](https://github.com/andy5995/mhwkb/tree/master/Knowledge_Base) directory.

Add at least three apps to the file. Some ideas are in a recent article by @desirottman: _[7 Tech-Driven Ways to Improve Your Mental Health](https://medium.com/ifme/7-tech-driven-ways-to-improve-your-mental-health-2ebc01557ca9)_

Please remember to "star" this project (upper right corner).

 See [CONTRIBUTING.md](https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md) for important information about **tagging guidelines** and **categorization**

**Comment by bealearnscode** [comment]
I would like to work on this.

**Comment by andy5995** [comment]
ok. :) Thanks!

**Comment by andy5995** [comment]
Completed (2533183349fc7bc0502b868d8f5e99b30538f8ea)
