### ISSUE TITLE
add 01open_source_software.md to the KB

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#17]
Please add `01open_source_software.md` to the [Knowledge Base](https://github.com/andy5995/mhwkb/tree/master/Knowledge_Base) directory.

Add at least four projects to the file. Be sure to add this one:
https://github.com/SunyataZero/mindfulness-at-the-computer

Please remember to "star" this project (upper right corner).

See https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md for help with pull requests.

**Comment by lauragift21** [comment]
Can i take this up?

**Comment by andy5995** [comment]
Yes, you may. :) Thank you @lauragift21 ...

**Comment by andy5995** [comment]
Closed by #23 , Thanks!
