### ISSUE TITLE
add `01music_therapy.md`

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#21]
Please add `01music_therapy.md` to the [Knowledge Base](https://github.com/andy5995/mhwkb/tree/master/Knowledge_Base) directory.

Some ideas can be found in @desirottman's article _[13 Songs to Reduce Anxiety & Stress](https://medium.com/ifme/13-songs-to-reduce-anxiety-stress-58eb9b362867)_

 Add at least three links to the file.

Please remember to "star" this project (upper right corner).

 See https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md for help with pull requests.

**Comment by seancyw** [comment]
Hi @andy5995, I would like to work on this issue :)

**Comment by andy5995** [comment]
Thanks @seancyw :)

**Comment by andy5995** [comment]
Closed by #24
