### ISSUE TITLE
center the text on the web site

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#32]
A lot of the CSS and html code is in

https://github.com/andy5995/mhwkb/blob/master/html_functions.c

It should be somewhat clear by looking at the other .c file how it's applied:

https://github.com/andy5995/mhwkb/blob/c16659583fee5a7647c22acc619eaa23a0b0872a/mhwkb_md2html.c#L163

It may be a bit confusing for those not familiar with C, but you'll see basically that the formatting is the same, just with a few extra chars. :)

Here's what the site looks like now: https://mhwkb.github.io/

We need some centering.. and probably some other ideas. If you like to play with html and css and have some ideas, please feel free to open some new tickets for separate ideas.

Please remember to "star" this project (upper right corner).

**Comment by andy5995** [comment]
Oh, and I'm sure it would be better to put the CSS code into a CSS file, having it load from the .html head, and remove it completely from the C 
source code.

**Comment by andy5995** [comment]
@Krazete may be working on this. So for right now, let's not make any more changes. (comments on #33)

**Comment by andy5995** [comment]
Ok, @Krazete made some changes to the centering.

Let's leave this be for now while @dafky2000 works on #36

**Comment by andy5995** [comment]
@Krazete I get the impression that #37 should be resolved before making any more changes to the stylesheet. Do you agree?

**Comment by Krazete** [comment]
Any changes to the CSS now would probably be easy enough to modify to fit any new HTML format later. But yeah, I'd say it's preferable to complete #37 first.

**Comment by dafky2000** [comment]
Honestly, I wouldn't worry about finishing #37 first so long as your changes are only to the CSS file contents :)

**Comment by andy5995** [comment]
@dafky2000 He'll need to access some of the html to make the design more sexy. We'll wait for you. :)

**Comment by dafky2000** [comment]
I will be a couple or few days before I get anywhere with this if that changes anything.

**Comment by andy5995** [comment]
Nope, doesn't change anything. Take your time. :)

**Comment by andy5995** [comment]
@Krazete the template you suggested has been implemented. Would you like to handle the initial HTML and CSS design? The color scheme and styles used now were mostly examples I copied and pasted from a CSS tutorial, and I'm not attached to the current colors or styles.

You're welcome to join the [chat room[(https://join.slack.com/t/mhwkb/shared_invite/enQtMjU3MjcwMTk4NjYzLTA0ZDc2YjAwMDJiNTU1YTBmYTViNmQ5MTdjOTk2MDA2MDMyMzNiYjU4ZWIzMTZlNmU4ZjFhNDg1MjQ5OGQyMjI).

**Comment by Krazete** [comment]
Yeah, the template is beautifully done. Thanks @dafky2000!
@andy5995 I'm slacking on my classes so I can only do some basic things.
Maybe you can close this issue and open up another one for general design and layout?

**Comment by andy5995** [comment]
@Krazete I see you've been able to make some changes. Thanks!  And yes, i can open another ticket.

Instead of pushing directly to the upstream, do a PR from your fork instead. PR's are easier to review, and will prevent too many pushes being done at one time.

**Comment by Krazete** [comment]
Ah, sorry. I'll do that next time.

**Comment by andy5995** [comment]
I did the same thing once when given collaborator access. ;) No worries.

**Comment by andy5995** [comment]
@Krazete just an FYI, you may have seen a message about a bug. There was some issue with the C code not processing article_link.html correctly after you added _class="tag". That's been fixed (andy5995/mhwkb#56), and all your changes are now live on the web site. Thanks.
