### ISSUE TITLE
make web pages "mobile-friendly"

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#36]
It seems that some web sites can detect if it's being viewed on a cell phone and auto switches from desktop version to mobile-friendly version.

I'd be satisfied with just a message that displays at the bottom "make page mobile-friendly".

The code for that would be needed.

When viewed on a cell phone right now, the biggest problem is that the font is too small.

https://mhwkb.github.io/

Please leave a message on this ticket if you're interested and you have some experience doing such a task.

Please remember to "star" this project (upper right corner).

 See [CONTRIBUTING.md](https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md) for important information.

**Comment by dafky2000** [comment]
Looks pretty straight forward, I should be able to do this either this evening or tomorrow morning quickly.

**Comment by andy5995** [comment]
Thanks @dafky2000 .

The web pages are generated by the C program, so I won't work on that today. :) Is it likely you'll be making many changes to the .CSS file?

**Comment by dafky2000** [comment]
I hope that I should only need to touch the CSS. I have experience with C if I need to add some HTML headers as well :)

**Comment by andy5995** [comment]
Cool. :)

I think the easiest way to test any new CSS is to clone the repo from where the html files are served: https://github.com/mhwkb/mhwkb.github.io

But submit your PR to this repo.

**Comment by SunyataZero** [comment]
Hi all, i haven't used this myself (i've been relying on themes like bootstrap to handle these things) but i think this may be useful: https://www.w3schools.com/css/css_rwd_mediaqueries.asp

**Comment by dafky2000** [comment]
I was going the media queries route but making the site "responsive" should suffice for the scope of this issue.
