### ISSUE TITLE
separate HTML from C code

### ISSUE THREAD

**Issue by Krazete** [andy5995/mhwkb#37]
There should be an HTML template separated (as much as possible) from the C code. The result should be something like this:
HTML Template File:
```html
<!DOCTYPE html>
<head>
<title>${title}<\title>
<\head>
<body>
${content}
<\body>
```
Article Template File:
```html
<div class="article">
  <h1>${article_title}<\h1>
  <p>${article_content}<\p>
  <span>${tags}<\span>
  ...
<\div>
```
C Code:
```c
html_template = open("HTML_Template.txt", "r");
article_template = open("Article_Template.txt", "r");
function build_content(article_title, article_content, tags, ...){
  char* content;
  sprintf(content, article_template, article_title, article_content, tags, ...);
  return content;
}
content = [
  build_content(article0),
  build_content(article1),
  build_content(article2),
  ...
]
fprintf(fp_index, html_template, title, content);
```
This [link](http://mo.notono.us/2008/07/c-stringinject-format-strings-by-key.html) might be helpful.
I hardly know anything about C though (and I apologize if my example code is rubbish), so I dunno if this is more or less manageable than the current code.

**Comment by andy5995** [comment]
Thanks for this suggestion @Krazete . Definitely need things to be more efficient, and makes it easier for multiple people to work at the same time.

And don't worry about your example code. Everything gets worked out over time. We're not too strict here, and examples like you gave are good starting points.

We need to wait for #36 to be finished before starting this.

I'll look over the info within the next few days hopefully. If anyone has experience making templates and would like to work on this, post a note here.

**Comment by andy5995** [comment]
@Krazete You've apparently read more on this subject than I have. Would you be interested in trying to work on this ticket? You mentioned you don't have much experience with C, but I can give you some guidance if improving your C skills is one of your goals.

**Comment by dafky2000** [comment]
@andy5995 I'll take seconds on this if @Krazete doesn't want it :) 

Are you opposed to using external libraries? I general prefer header-only libraries but I'm not entirely sure what is out there other than Mustach (http://mustache.github.io/) (c implementation: https://gitlab.com/jobol/mustach).

**Comment by andy5995** [comment]
No, I'm not opposed to external libraries if that would be easiest for you to get the job done.

The main consideration is that only HTML and JS can be used for the web site (afaik). We can use binaries to generate the html files and templates, and then they get uploaded to the server (which I do manually).

Is that basically what you have in mind?

**Comment by andy5995** [comment]
@Krazete assuming dafky2000 is going to take this ticket, please let me know if you'd like to work with C a bit more and I'll keep it in mind for future tickets.

**Comment by dafky2000** [comment]
Basically, I noticed that's what is already being done so I'll try to keep it in the same spirit, one change at a time / per issue :)

Don't worry about (not) working on files at the same time, this one may take a minute. I'll keep up to date and resolve merge conflicts as I go!

Perfect prep work with the src and templates directories :)

**Comment by andy5995** [comment]
@dafky2000 I'd strongly recommend syncing your repo first
https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md#syncing

And then following the procedure for PR's above it. Should make things quite a bit easier in the long-term, and that procedure works great for working on most any project on GitHub. A great way to help prevent merge conflicts. ;)

Oh, thanks for noticing my prep work. :)

**Comment by andy5995** [comment]
Since you're fork is already one commit ahead because of your previous patch, you may get some errors when trying to `git merge upstream/master'

If that happens use `git reset --hard c6ac335dd4d009ca0334f91dee81946034a5187f`

Then try merging the upstream again.

The first time you push the master branch after that, use 'push -f`. After that, you shouldn't need the -f (force) when you push your fork/master branch.

(Don't read all of the above until the time comes, otherwise it's very confusing!)
