### ISSUE TITLE
Create xml feed

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#44]
Here's the format, pretty basic, but it [validates](https://validator.w3.org/feed/#validate_by_input).

```<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <atom:link href="https://mhwkb.github.io/rss.xml" rel="self" type="application/rss+xml" />
        <title>Mental Health and Wellness KB</title>
        <description>Share a diverse amount of viewpoints</description>
        <link>https://mhwkb.github.io/</link>
        <item>
            <title>selfcare.tech</title>
            <guid>http://selfcare.tech</guid>
            <link>http://selfcare.tech</link>
            <pubDate>Thu, 12 Oct 2017 12:00:00 GMT</pubDate>
            <description>"selfcare", "collaborative", "resources", "directory", "technology"</description>
        </item>
        <item>
            <title>Black Dog Institute</title>
            <guid>https://www.blackdoginstitute.org.au/</guid>
            <link>https://www.blackdoginstitute.org.au/</link>
            <pubDate>Wed, 11 Oct 2017 12:00:00 GMT</pubDate>
            <description>"workplace", "community", "resources", "directory", "education", "training", "research"</description>
        </item>
        <item>
            <title>Beyond Blue</title>
            <guid>https://www.beyondblue.org.au/</guid>
            <link>https://www.beyondblue.org.au/</link>
            <pubDate>Wed, 11 Oct 2017 12:00:00 GMT</pubDate>
            <description>"Australia", "chat", "forum", "resources", "LGBTQ", "Aboriginal and Torres Strait Islander people", "community", "youth", "pregnancy", "seniors"</description>
        </item>
        <item>
            <title>Men: how to have a conversation with a mate about mental health</title>
            <link>https://www.health.qld.gov.au/news-alerts/news/men-how-to-have-conversation-mate-mental-health</link>
            <guid>https://www.health.qld.gov.au/news-alerts/news/men-how-to-have-conversation-mate-mental-health</guid>
            <pubDate>Wed, 11 Oct 2017 12:00:00 GMT</pubDate>
            <description>"men", "friendships", "mates", "providing support", "advice", "Australia"</description>
        </item>
        <item>
            <title>R U OK?</title>
            <guid>https://www.ruok.org.au/</guid>
            <link>https://www.ruok.org.au/</link>
            <pubDate>Wed, 11 Oct 2017 12:00:00 GMT</pubDate>
            <description>communication", "support", "suicide prevention", "crisis", "directory", "resources", "Australia"</description>
        </item>
    </channel>
</rss>
```

a `<link>` tag will need to be added to the `<head>` and the pages will need some small rss icons.

But don't start on this until #37 is done. We can discuss a few things about it though. ;)

**Comment by andy5995** [comment]
I found some problems with the feed. Fixed, and added four more items.

**Comment by andy5995** [comment]
@UnicornRiley 

>a `<link>` tag will need to be added to the `<head>`

The code is one line. I'll be telling you which file to add it to. usually it would go directly in the html file, like so... : http://www.rssboard.org/rss-autodiscovery

Same with this:

>the pages will need some small rss icons

rss icons that are hyperlinked to the feed URL, one at the top of each page, one at the bottom.

And again, I'll be telling you into which file to put the code. The files are being worked on atm.

Is that more clear?

**Comment by UnicornRiley** [comment]
Sure,  I can.

**Comment by baohouse** [comment]
I suggest putting tags in the <category> element.

**Comment by andy5995** [comment]
Good idea @baohouse 

I think this feed should be auto-generated instead.

When new links are added to the KB, they can be manually copied to  "recently_added.md" (doesn't exist yet) in the same PR.

The feed would be generated at the same time the other html files are generated.

The date string for `<pubDate>` could be passed from the command line as argv[2].
* Problem: it would use the same date for all items

It'll be more clear on how to implement this after #37 is completed by @dafky2000

**Comment by andy5995** [comment]
I think the existing feed will be adequate, if not ideal. Maybe we'll revisit this in the future.
