### ISSUE TITLE
general web site layout

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#6]
What I see is that the home page would link to the top categories (the .json files).

If one goes to view "communities", the list will display.

Basically the goal would be something similar to a categorized directory such as this: https://psychcentral.com/resources/

But using tags that might help narrow a search.

It would be nice is links were displayed randomly, not alphabetically. So users have more opportunities to see sites that otherwise would be at the end of the list.

Alphabetical by default, user could select "randomize".

Open for discussion...

**Comment by SunyataZero** [comment]
Are you limited to static sites (in other words html+js) or is it possible to use different hosting than github? (and then maybe using drupal or plone for example?)

**Comment by andy5995** [comment]
I would like to stick with free, reliable hosting. I don't know what kind of permissions GitHub allows users yet (i.e. what scripts can be run, if I can use server side includes, what file types are allowed). I haven't investigated the options you mentioned in #1 yet. I'll let the matter rest for a bit and talk things over with you more (I need to clear my head). Thanks a lot for helping me figure this out, @SunyataZero  :)

I converted the json files to markdown (#14) , but I made sure a program can still parse the data easily once ideas on the end-game are more developed.

**Comment by SunyataZero** [comment]
Github unfortunately doesn't support any server-side code, so basically only html+js. I have some experience with Drupal and WordPress but i don't know how to find cost-free hosting, i've used shared hosting myself when running and helping out with different projects, which is pretty cheap but not cost-free. Kind Regards, Tord

**Comment by andy5995** [comment]
Thanks @SunyataZero . I'm still thinking about the web site. But here is a related post #25

**Comment by andy5995** [comment]
# Updated 2017-10-07
## Basic design
### Home page
* Three columns, 20 links in each column (randomized if possible)
  * pagination (next <-> previous
* clicking on a tag will bring up a new page
  * three columns 20 links per column (randomized)
  * pagination
* Language selection
  * I opened an issue to add links in other languages (#22)

### external RSS feeds
* I don't know how well they'd fit in now. maybe consider not incorporating them.
* Display one headline from 10 random feeds.
  * button next to each headline, gives option to display all the headlines from that feed
  * insert into a row, underneath the three columns

**Comment by andy5995** [comment]
First web site is live. Very pre-alpha-ish ;)
https://mhwkb.github.io/

The code that generated most of it: https://github.com/andy5995/mhwkb/blob/master/mhwkb_md2html.c

**Comment by andy5995** [comment]
This is being discussed in #36 #37 #38 and #32

**Comment by andy5995** [comment]
I think this ticket has been rendered irrelevant. Thanks @SunyataZero
