### ISSUE TITLE
Update simplectemplate from develop

### ISSUE THREAD

**Issue by dafky2000** [andy5995/mhwkb#62]
This will require changing the functions calls of `render_template` to `render_template_file`. I may not have time for this in the next few day but I also likely wont be pushing that to master in that time either. When I have time I'll fix this before I push to master but anyone is welcome to take care of it :).

**Comment by dafky2000** [comment]
https://github.com/dafky2000/simplectemplate/tree/develop

**Comment by andy5995** [comment]
@dafky2000 Thanks for opening this ticket. I may take care of it if you need to save some time. How about if we touch base about it in a few days if no one else takes the ticket?

Re: using the label `up-for-grabs`; we're listed on the [Up For Grabs](http://up-for-grabs.net/#/) site. These are some guidelines they recommend:

```We're looking for projects who can take the time out to help mentor developers as they get started with open source.

What sort of tasks are a good fit?

    Tasks should take no longer than a few nights' worth of work
    Tasks should stand alone - avoid core functionality on which other tasks depend
    Tasks should be well described with pointers to help the implementer
```
Could you explain in more detail what this patch involves?

**Comment by dafky2000** [comment]
@andy5995 This patch provides template rendering from a string. Previously, you could only render from a file, so now, `render_template_file` simply retrieves the file contents and calls `render_template`. I hope to keep breaking changes to a minimum but this one had to happen now rather than later.

* Rename function calls in https://github.com/andy5995/mhwkb/blob/master/src/mhwkb_md2html.c
  * `render_template` to `render_template_file`
* Copy and overwrite `template_functions.h` and `template_functions.c` from the simplectemplate develop branch https://github.com/dafky2000/simplectemplate/tree/develop.

That should be it!

**Comment by andy5995** [comment]
@parthsuresh mentioned he was more interested in C than html/css. Parth, would you want to take this ticket after you're done with #38 ?
