### ISSUE TITLE
add existing (temporary) RSS feeds

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#63]
@UnicornRiley Could add these two feeds?

https://github.com/mhwkb/mhwkb.github.io/commits/master.atom
https://github.com/andy5995/mhwkb/commits/master.atom

That requires 2 lines be added between the head tags, One line for each feed

You can use this, edit as needed.

```
<link rel="alternate" type="application/rss+xml" title="RSS"
      href="http://feeds.feedburner.com/TheRssBlog">
```

For _title_ use "Temporary RSS feed"

You can put those lines below L7 in this file https://github.com/andy5995/mhwkb/blob/f301eb20dc590a845a9482ddf8d14ab9fca88bbb/templates/index.html#L7

And then add regular hyperlinks to the footer at 
https://github.com/andy5995/mhwkb/blob/f301eb20dc590a845a9482ddf8d14ab9fca88bbb/templates/index.html#L13

You can use a 24x24 rss icon from http://www.iconarchive.com/search?q=rss&res=24

So the end result would be two lines displayed in the footer:
rss icon (space or padding), `link`

The text for the links can be "Temporary RSS feed 1" and "...2"

**Comment by erichoog** [comment]
@andy5995 is this partly covered by this commit? https://github.com/andy5995/mhwkb/pull/68/files#diff-fb5aa1cd1261d08d02db6f7dc314d9ab

I could add another RSS link and label the two differently.

**Comment by andy5995** [comment]
Thanks for the offer @erichoog , I had decided to add the second one to the README but not use it on the web site.

Forgot to close the ticket.
