### ISSUE TITLE
docs for testing CSS/generating html

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#67]
@erichoog wrote in #61 
>I think those steps should be added to the documentation for more clarify for new users/contributors.

Yes, I was thinking of that since you mentioned the other night it took you a while to figure out how the site was generated. The program was written just a few days ago and had a major upgrade 2 days ago, so documentation hasn't been put in place yet. Would you like to do a PR to add an outline of the process?

**Comment by erichoog** [comment]
I could certainly do this when i have a few spare moments.  If anyone else wants to they can also go ahead if I haven't done this yet.

**Comment by andy5995** [comment]
Thanks @erichoog . I've labeled the ticket accordingly. (it's up-for-grabs, atm)

Eric, though I haven't merged one of your PRs yet, I still consider you a contributor because of the info and POV you've presented. You can add yourself to https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTORS.md if you like.
