### ISSUE TITLE
Should we implement Bootstrap 3 for CSS?

### ISSUE THREAD

**Issue by erichoog** [andy5995/mhwkb#69]
We are trying to determine if there is any thoughts from the community on implementing Bootstrap 3 for the CSS of the site.  Does any one have any input on this?

Please see the screenshots and conversation on PR #68 for some context.

Is implementing Bootstrap overkill for a simple site like this?

If we do should we reference the CDN's or download the source files and include them in the project?

**Comment by Krazete** [comment]
I was able to replicate those screenshots with plain CSS (and a bit of HTML restructuring) in ~10 minutes, so on one hand I second @andy5995's opinion and I'd say it's overkill.

On the other hand, using Bootstrap would ensure the website looks good across all browsers, be it desktop or mobile.

But then again, for a website this simple in structure, it wouldn't be hard at all to fix cross-browser discrepancies by adding rules to the CSS manually.

**Comment by andy5995** [comment]
Thanks for your perspective @Krazete . That the site looks good across all browsers is important to me.

Typically when I host projects, I like to provide people opportunities to learn and practice.

I  guess I had better make a decision. If @UnicornRiley is unable to start giving us an initial design by Friday night, I'll merge the PR @erichoog submitted.

If we wind up not using bootstrap now, we can always reconsider later, depending on how much the site is built-up, etc. It's a good project and I'm grateful that Eric presented it.

I particularly liked the "rounded" corners on the tags, and the small icons (home and info) on the footer links. :)

I'll leave this ticket open if anyone wants to add more opinions.

**Comment by Krazete** [comment]
If Bootstrap is used, I recommend reading [this](https://stackoverflow.com/questions/26192897/should-i-use-bootstrap-from-cdn-or-make-a-copy-on-my-server).

**Comment by erichoog** [comment]
@Krazete having some redundancy there if we did end up using Bootstrap would be a great idea.

Thanks for the link!

I guess I'm a little biased on this topic because I'm a fan of using Bootstrap but always open to other schools of thought!

**Comment by andy5995** [comment]
>having some redundancy there if we did end up using Bootstrap would be a great idea.

@erichoog , UnicornRiley seems to be MIA. I haven't heard from him in several days. We'll use Bootstrap. Can you set up that redundancy thing before I merge the PR? And make the tags oval-shaped?

For now, we'll do single column, but I like the 3-column idea and we'll probably revisit that soon.

**Comment by erichoog** [comment]
sounds good i'll work on that
