### ISSUE TITLE
tags.txt needs updating

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#78]
https://github.com/andy5995/mhwkb/blob/38f1eb9b68bc7748d44cd4561dab9a566af8f681/tags.txt#L5

This can be done by
1.  forking the repo where the html files are stored: https://github.com/mhwkb/mhwkb.github.io

2. Clone the repo to your computer

3. Use `dir` or `ls` to [redirect the output to a text file](https://www.lifewire.com/how-to-redirect-command-output-to-a-file-2618084).

4. Load the file into a text editor and do a search and replace: `.html` to NULL

5. delete the lines with `README`, `LICENSE`, and `mhwkb_style.css`

6. Copy in the header of the existing tags.txt file from this repo.

7. Change the last update time. then you can rename that file to tags.txt

8. You don't need to do a [PR](https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md#pull-requests) on that repo - do it on this one.

Please remember to **"star"** this project (upper right corner) and feel free to [join the project chat room](https://join.slack.com/t/mhwkb/shared_invite/enQtMjU3MjcwMTk4NjYzLTA0ZDc2YjAwMDJiNTU1YTBmYTViNmQ5MTdjOTk2MDA2MDMyMzNiYjU4ZWIzMTZlNmU4ZjFhNDg1MjQ5OGQyMjI).

See [CONTRIBUTING.md](https://github.com/andy5995/mhwkb/blob/master/CONTRIBUTING.md) for important information about first-time contributions and proper PR procedure.

**Comment by moidmw** [comment]
As in replace `.html` extenstion to `NULL` text..? @andy5995

**Comment by erichoog** [comment]
@moidmw I'm not 100% but I think he meant replace .html with nothing.  Looking at the previous entries it looks like the .html was just removed from the file names.

**Comment by moidmw** [comment]
I too thought that but going by the intstruction it says to "replace".. that is what is confusing. @erichoog

**Comment by andy5995** [comment]
@erichoog wrote:
>@moidmw I'm not 100% but I think he meant replace .html with nothing. Looking at the previous entries it looks like the .html was just removed from the file names. Hope that helps!

Exactly!
