### ISSUE TITLE
how to display the date field on the web site

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#90]
The date field that displays with each link needs some design. I don't have anything in mind, but if you have some ideas, please post them here. Thanks.

**Comment by jamielthompson29** [comment]
Maybe I could make a switch to write the date out, i.e. "date: 2012-11-23" could be "November 23, 2012" & if there isn't a date, maybe just have nothing there instead of "date: n/a"

**Comment by andy5995** [comment]
Thanks for the suggestions @jamielthompson29 . Per our discussion in Slack, the dates will be removed (#109)
