### ISSUE TITLE
When viewed in Firefox for android, tags don't wrap on tag dot html pages

### ISSUE THREAD

**Issue by andy5995** [andy5995/mhwkb#92]
When viewed in Firefox for android, tags don't wrap on tag dot html pages

I didn't test it yet in other mobile browsers.

The list exceeds the right border of my cell phone.

This is likely due to the C source code. If anyone know of another cause, let me know. But I'll investigate our code a bit more and give an update here.

**Comment by erichoog** [comment]
@andy5995 I beleive it is due to this change:

https://github.com/andy5995/mhwkb/commit/50c12ff9d99c04181115d8aec9345494b35c495a#diff-803c5170888b8642f2a97e5e9423d399

**Comment by andy5995** [comment]
The same result happens in Chrome for android.

I'm going to clean up the code a bit today. Looks like some newlines would fix the problem on the tag pages.

Here's the html code difference

## index.html

```
<div class="article-bottom">
          <span class="date">date: na<br />
</span>
          <a class="tag label label-danger" href="open_source.html">open_source</a>
<a class="tag label label-danger" href="blogs.html">blogs</a>
<a class="tag label label-danger" href="directories.html">directories</a>

      </div>
```

## tag dot html

```
      <div class="article-bottom">
          <span class="date">date: na<br />
</span>
          <a class="tag label label-danger" href="open_source.html">open_source</a><a class="tag label label-danger" href="blogs.html">blogs</a><a class="tag label label-danger" href="directories.html">directories</a>
      </div>
```
